// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEibjBuiZXBVxVaJZIhetqfQnAVrsLjvU',
    appId: '1:278002367977:web:02faf3f986e91a18c89f78',
    messagingSenderId: '278002367977',
    projectId: 'capstone1-489b0',
    authDomain: 'capstone1-489b0.firebaseapp.com',
    storageBucket: 'capstone1-489b0.appspot.com',
    measurementId: 'G-5XDMD2JB8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0GRC_unmMjJ0WnVDUwSJzxjJFctfUOa4',
    appId: '1:278002367977:android:ae3936c51b109458c89f78',
    messagingSenderId: '278002367977',
    projectId: 'capstone1-489b0',
    storageBucket: 'capstone1-489b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZRvklpxy3ft-sOH2-ojrXMfirIPFyOKg',
    appId: '1:278002367977:ios:6180735713a5d948c89f78',
    messagingSenderId: '278002367977',
    projectId: 'capstone1-489b0',
    storageBucket: 'capstone1-489b0.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZRvklpxy3ft-sOH2-ojrXMfirIPFyOKg',
    appId: '1:278002367977:ios:6180735713a5d948c89f78',
    messagingSenderId: '278002367977',
    projectId: 'capstone1-489b0',
    storageBucket: 'capstone1-489b0.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEibjBuiZXBVxVaJZIhetqfQnAVrsLjvU',
    appId: '1:278002367977:web:786b8ca074c452c1c89f78',
    messagingSenderId: '278002367977',
    projectId: 'capstone1-489b0',
    authDomain: 'capstone1-489b0.firebaseapp.com',
    storageBucket: 'capstone1-489b0.appspot.com',
    measurementId: 'G-M1BJNE68XZ',
  );
}
